version: '3.8'

services:
  jewelrybox-ai:
    build: .
    container_name: jewelrybox-ai-bot
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=*
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistence (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - jewelrybox-network

networks:
  jewelrybox-network:
    driver: bridge 