version: '3.8'

services:
  diamond-family-assistant-staging:
    build: .
    container_name: diamond-family-assistant-staging
    ports:
      - "8001:8000"  # Different port for staging
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - PORT=8000
      - HOST=0.0.0.0
      - ENVIRONMENT=staging
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis-staging
    networks:
      - diamond-family-staging-network

  # Optional: Redis for staging session storage (if needed for multi-user testing)
  redis-staging:
    image: redis:7-alpine
    container_name: diamond-family-redis-staging
    ports:
      - "6380:6379"  # Different port for staging Redis
    volumes:
      - redis_staging_data:/data
    networks:
      - diamond-family-staging-network

volumes:
  redis_staging_data:

networks:
  diamond-family-staging-network:
    name: diamond-family-staging-network 