version: '3.8'

services:
  diamond-family-assistant:
    build: .
    container_name: diamond-family-assistant
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - PORT=8000
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistence (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - diamond-family-network

networks:
  diamond-family-network:
    driver: bridge 