version: '3.8'

services:
  jewelrybox-ai-staging:
    build: .
    container_name: jewelrybox-ai-staging
    ports:
      - "8001:8000"  # Different port for staging
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - ENVIRONMENT=staging
      - BRANCH=web-search
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "staging=true"
      - "branch=web-search"
      - "purpose=pre-production-testing"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for staging session storage (if needed for multi-user testing)
  redis-staging:
    image: redis:7-alpine
    container_name: jewelrybox-redis-staging
    ports:
      - "6379:6379"
    restart: unless-stopped
    profiles:
      - full-stack  # Only starts with: docker-compose --profile full-stack up

networks:
  default:
    name: jewelrybox-staging-network 